name: CI
on:
  push:
    branches: ["development"]

jobs:
  build-and-push:
    environment: development
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate .env
        run: |
          echo PORT=${{ vars.PORT }} >> .env

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.IMAGE_NAME }}:latest .

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ vars.IMAGE_NAME }}:latest
