name: CI
on:
  push:
    branches: ["development"]

jobs:
  build-and-push:
    environment: development
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate .env
        run: |
          echo ${{ vars.ENV_FILE }} >> .env

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.IMAGE_NAME }}:latest .

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ vars.IMAGE_NAME }}:latest

  deployment:
    needs: build-and-push
    environment: development
    runs-on: ubuntu-22.04
    steps:
      - name: Setup in Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD}}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop $(docker ps -q --filter "publish=${{ vars.PORT }}")
            docker rm $(docker ps -a -q --filter ancestor=${{ vars.IMAGE_NAME }}:latest)
            docker rmi ${{ vars.IMAGE_NAME }}:latest
            docker pull ${{ vars.IMAGE_NAME }}:latest
            docker run -d --restart=always -p ${{ vars.PORT }}:${{ vars.PORT }} ${{ vars.IMAGE_NAME }}:latest
